name = "AstroFit"
uuid = "42f8b41a-0540-4923-ba10-9f50750fcd79"
version = "0.1.0"
authors = ["Matteo Sapori <matteosap@hotmail.com>"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extensions]
AstroFitDistributionsExt = "Distributions"
AstroFitOptimizationExt = ["Optimization", "ForwardDiff"]
AstroFitPigeonsExt = ["Pigeons", "LogDensityProblems"]

[compat]
Accessors = "0.1"
Distributions = "0.25"
ForwardDiff = "1.3.3"
LogDensityProblems = "2"
Optimization = "5"
OptimizationOptimJL = "0.4"
Pigeons = "0.4"
Test = "1"
TestItemRunner = "1"
julia = "1.9"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner", "Distributions", "ForwardDiff", "LogDensityProblems", "Optimization", "OptimizationOptimJL", "Pigeons"]
